#!/bin/sh

# Set default values for variables (-v), but -i is optional
DEFAULT_ENV="STAGING"
DEFAULT_BROWSER="CHROME_HEADLESS"
DEFAULT_RUN_ON_FAILURE="NONE"

# Create a temporary argument file
args_file="args.txt"
> "$args_file"  # Clear the file before appending new arguments

# Set default arguments for variables
echo "-v ENV:$DEFAULT_ENV" >> "$args_file"
echo "-v BROWSER:$DEFAULT_BROWSER" >> "$args_file"
echo "-v RUN_ON_FAILURE:$DEFAULT_RUN_ON_FAILURE" >> "$args_file"
echo "ARGS: $@"

# Parse command-line arguments dynamically
test_suites=""  # Store test suite paths as a string
include_tags=""  # Store all include tags
exclude_tags=""  # Store all include tags
RERUNFAILED=""  # Variable to track --rerunfailed
RERUNFAILED_FILE="" # File for --rerunfailed

while [ $# -gt 0 ]; do
    case $1 in
        --rerunfailed)
            RERUNFAILED="--rerunfailed"
            RERUNFAILED_FILE="$2"
            shift 2
            ;;
        -i)  
            # Append new tag to existing tags with space separation
            if [ -z "$include_tags" ]; then
                include_tags="-i '$2'"
            else
                include_tags="$include_tags -i '$2'"
            fi
            shift 2
            ;;
        -e)  
            # Append new tag to existing tags with space separation
            if [ -z "$exclude_tags" ]; then
                exclude_tags="-e '$2'"
            else
                exclude_tags="$exclude_tags -e '$2'"
            fi
            shift 2
            ;;
        
        -v)  
            case "$2" in
                ENV:*)
                    ENV_VALUE="${2#ENV:}"
                    sed -i "s|-v ENV:$DEFAULT_ENV|-v ENV:$ENV_VALUE|" "$args_file"
                    ;;
                BROWSER:*)
                    BROWSER_VALUE="${2#BROWSER:}"
                    sed -i "s|-v BROWSER:$DEFAULT_BROWSER|-v BROWSER:$BROWSER_VALUE|" "$args_file"
                    ;;
                RUN_ON_FAILURE:*)
                    RUN_ON_FAILURE_VALUE="${2#RUN_ON_FAILURE:}"
                    sed -i "s|-v RUN_ON_FAILURE:$DEFAULT_RUN_ON_FAILURE|-v RUN_ON_FAILURE:$RUN_ON_FAILURE_VALUE|" "$args_file"
                    ;;
                *)
                    echo "-v $2" >> "$args_file"
                    ;;
            esac
            shift 2
            ;;
        *)  
            test_suites="$test_suites $1"
            shift
            ;;
    esac
done
echo "RERUNFAILED: $RERUNFAILED"
echo "RERUNFAILED_FILE: $RERUNFAILED_FILE"
echo "test_suites: $test_suites"
echo "include_tags: $include_tags"
echo "exclude_tags: $exclude_tags"

# Check if rerunfailed is set and if the rerun file is provided
if [ -n "$RERUNFAILED" ] && [ -n "$RERUNFAILED_FILE" ]; then
    # robot --outputdir result --output preprocess_output.xml $RERUNFAILED "result/preprocess_output.xml" --argumentfile "$args_file" automation-web/Genesis/Pre-process
    pabot --processes 6 --outputdir result --output output.xml $RERUNFAILED "$RERUNFAILED_FILE" --argumentfile "$args_file" $test_suites
    # pabot --processes 8 --testlevelsplit --outputdir result --output postprocess_output.xml $RERUNFAILED "result/postprocess_output.xml" --argumentfile "$args_file" automation-web/Genesis/Post-process
else
    # Run robot for pre-process execution (only with ENV and BROWSER)
    # robot --outputdir result --output preprocess_output.xml --argumentfile "$args_file" automation-web/Genesis/Pre-process
    
    # Run pabot with full arguments (including -i if provided) and test suites
    eval "pabot --processes 6 --outputdir result --output output.xml $include_tags $exclude_tags --argumentfile \"$args_file\" $test_suites"
    
    # Run robot for post-process execution (only with ENV and BROWSER)
    # pabot --processes 8 --testlevelsplit --outputdir result --output postprocess_output.xml --argumentfile "$args_file" automation-web/Genesis/Post-process
fi

# Merge reports generated by pabot and additional test suites
# rebot --outputdir result result/preprocess_output.xml result/main/main_output.xml result/postprocess_output.xml
